// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": "Начало",
  "static": "Статичен",
  "infinite": "Безкраен",
  "fetch": "Безкраен Динамичен",
  "switchLang": "Смени езика"
};
export default messages;